security:
    encoders:
        App\UserAccount\User:
            algorithm: auto
    providers:
        users:
            entity:
                class: 'App\UserAccount\User'
                property: 'email'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        register_and_auth:
            pattern: ^/api/v1/(fr|en)/users
            anonymous: true
        main:
            anonymous: false
            logout: ~
            guard:
                authenticators:
                    - App\UserAccount\ApiTokenAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
