#index:
#    path: /
#    controller: App\Controller\DefaultController::index

## USER
users_registration:
    path: /api/v1/{_locale}/users
    controller: App\UserAccount\RegistrationController
    methods: [POST]
    requirements:
        _locale: en|fr